
env = Environment()
#env = Environment(tools = ['mingw'])

target   = 'SimpleMeloTerm'
sources  = ['serial_example.cc', 'serial.cc', 'impl/win.cc', 'impl/list_ports/list_ports_win.cc', './../melo/melo.c']
libs     = ['setupapi.lib', 'ole32.lib', 'advapi32.lib']
libpath  = ['lib/']
includes = ['serial/', 'serial/impl', './../melo/']
defines  = ['MELO_CFG_MODE_MASTER']

env.Append(CPPDEFINES = defines)
#env['CCFLAGS'] = '-g'

env.Program(target = target, source = sources, CPPPATH = includes , LIBS = libs, LIBPATH = libpath)